### ISSUE TITLE
Public release checklist

### ISSUE THREAD

**Issue by jspahrsummers** [Carthage/Carthage#62]
- [x] Reach out to CocoaPods folks ahead of time
- [x] Tease about Carthage on Twitter, prior to opening it up
- [x] Publish GitHub release, along with a [pkg installer](https://github.com/Carthage/Carthage/issues/85)
- [x] Change repo tagline
- [x] Dark ship the org (make everything public, with no announcement)
- [x] Actually, officially announce everything
